fix: Made changes in grammar.pegjs for the strikedown approach
RocketChat/fuselage pull request #1256
Opened 2024-01-01 12:15 UTC by Subhojit-Dey1234

## Proposed changes (including videos or screenshots)
The required result for the corresponding codes changes.
![Screenshot from 2024-01-01 17-37-53](https://github.com/RocketChat/Rocket.Chat/assets/66687621/fded0fff-3da1-4532-83fd-62cadd675a89)

## Issue(s)
#1213 

## Steps to test or reproduce
Please follow the #1213

2024-01-01 12:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/fuselage?pullRequest=1256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/fuselage?pullRequest=1256) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/fuselage?pullRequest=1256) it.</sub>

2024-01-12 19:36 UTC, hugocostadev requested changes
Please, add some tests to it

2024-01-13 14:23 UTC, Subhojit-Dey1234 commented
Hi @hugocostadev, added the test cases for the corresponding code changes.

2024-01-15 13:24 UTC, hugocostadev approved these changes

2024-01-15 13:24 UTC, merged