chore: Add `eslint-plugin-jsx-a11y` plugin
RocketChat/fuselage pull request #1348
Opened 2024-04-03 19:11 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

2024-12-11 18:06 UTC, juliajforesti requested changes

2024-12-11 18:06 UTC, juliajforesti commented on packages/fuselage/src/components/Sidebar/SidebarBanner.tsx
> +          role='link'
is it really always a link?

2024-12-11 18:06 UTC, juliajforesti commented on packages/fuselage/src/components/SidebarV2/SidebarLink.tsx
> +    tabIndex={0}
are these attributes needed here? the element is already `<a />` - which has role link and tabIndex 0 by default, isn't it?

2024-12-18 19:53 UTC, dougfabris commented on packages/fuselage/src/components/Sidebar/SidebarBanner.tsx
> +          role='link'
adding it conditionally

2024-12-18 19:57 UTC, juliajforesti approved these changes

2024-12-18 19:59 UTC, merged