feat(fuselage): new set of `SidePanel` components
RocketChat/fuselage pull request #1359
Opened 2024-04-12 13:09 UTC by juliajforesti

[SIDE-4](https://rocketchat.atlassian.net/browse/SIDE-4)

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

[SIDE-4]: https://rocketchat.atlassian.net/browse/SIDE-4?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-04-23 05:50 UTC, subhamkumarr approved these changes

2024-04-23 21:08 UTC, dougfabris requested changes

2024-04-23 21:08 UTC, dougfabris commented on packages/fuselage/src/components/SidePanel/SidePanelListItem.tsx
missing the ref

2024-04-23 21:08 UTC, dougfabris commented on packages/fuselage/src/components/SidePanel/SidePanelList.tsx
missing the ref

2024-04-24 14:05 UTC, juliajforesti commented on packages/fuselage/src/components/SidePanel/SidePanelListItem.tsx
🤡

2024-04-24 14:05 UTC, juliajforesti commented on packages/fuselage/src/components/SidePanel/SidePanelList.tsx
🤡

2024-04-24 14:08 UTC, dougfabris approved these changes
LGTM!

2024-04-24 14:39 UTC, merged