feat(fuselage): Introduce `Callout` actions
RocketChat/fuselage pull request #1415
Opened 2024-07-24 20:19 UTC by dougfabris

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

2024-07-25 13:40 UTC, juliajforesti requested changes

2024-07-25 13:40 UTC, juliajforesti commented on packages/fuselage/src/components/Callout/Callout.styles.scss
> -    overflow: hidden;
won't this be a problem? 👀

2024-07-25 16:43 UTC, dougfabris commented on packages/fuselage/src/components/Callout/Callout.styles.scss
> -    overflow: hidden;
gracias! 🙇

2024-07-31 19:13 UTC, juliajforesti approved these changes

2024-07-31 19:13 UTC, juliajforesti approved these changes

2024-08-01 14:20 UTC, merged