chore: Upgrade Storybook
RocketChat/fuselage pull request #1424
Opened 2024-08-05 17:29 UTC by tassoevan

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

2024-08-06 18:10 UTC, dougfabris requested changes
why not creating a `customRender` to override render method used on the tests instead of adding `legacyRoot` in every single test file?

2024-08-06 19:54 UTC, tassoevan commented on packages/fuselage/src/components/PaletteStyleTag/helpers/getPalette.ts
I've replace Babel with SWC in Storybook builds... It complains that JSON imports only offer a default value (which makes more sense, since a valid JSON value like `"banana"` would not be destructurable).

2024-08-06 19:57 UTC, dougfabris commented on packages/fuselage/src/components/PaletteStyleTag/helpers/getPalette.ts
makes sense

2024-08-07 17:54 UTC, dougfabris approved these changes
<img width='320px' src='https://media1.tenor.com/m/K4os6LODv7wAAAAC/muchas-gracias-thank-you.gif' />

2024-08-07 21:46 UTC, merged