docs: Fuselage usage docs and npm links fix
RocketChat/fuselage pull request #700
Opened 2022-04-14 19:51 UTC by sidmohanty11

- Added docs about "how to use fuselage icons" in a project
- Added a note section about the possible error we might face while developing an application with Next.js and Fuselage
- Fixed all the npm links on the first page of the repository

## Issue(s)
closes #640

## Further comments

2022-07-11 23:56 UTC, dougfabris requested changes
Let's move the additional info to `fuselage-icons` context!

2022-07-12 12:30 UTC, sidmohanty11 commented
@dougfabris should I keep this part under fuselage or also shift it to icons

"
Note: If you are using Next.js for development and wish to use Rocket.Chat Fuselage components, you need to dynamically import the component. More on this can be found [here](https://dev.to/vvo/how-to-solve-window-is-not-defined-errors-in-react-and-next-js-5f97#3-third-solution-dynamic-loading).

For example,

```javascript
import dynamic from 'next/dynamic';
export const TextInput = dynamic(
  () => import('@rocket.chat/fuselage').then((module) => module.TextInput),
  { ssr: false }
);
```
"

2022-07-12 13:52 UTC, dougfabris commented
> And under icons, should I add the info like this, "
> 
> ### Usage
> To use the fuselage icons, you need to import the css first:
> 
> ```css
> @import url('@rocket.chat/icons/dist/rocketchat.css');
> ```
> 
> then you can use,
> 
> ```js
> <Icon name="hash" size="x20" />
> ```
> 
> "
> 
> Thank you

Yes, let's keep the information related to nextJS on fuselage.

About the icon, we can say we recommend the usage of the fuselage component but you can also add something like:
`<i class='rcx-icon'>{icon}</i>`

2022-08-10 18:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/fuselage?pullRequest=700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/fuselage?pullRequest=700) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/fuselage?pullRequest=700) it.</sub>

2022-10-21 21:43 UTC, dougfabris approved these changes

2022-10-21 21:45 UTC, merged