fix(fuselage): update optionTitle component styles
RocketChat/fuselage pull request #790
Opened 2022-07-26 19:02 UTC by guijun13

## Proposed changes (including videos or screenshots)

- Update padding block values of `OptionTitle`

## Issue(s)

## Further comments

2022-08-01 18:28 UTC, dougfabris requested changes

2022-08-01 18:28 UTC, dougfabris commented on packages/fuselage/src/components/Dropdown/DropdownDesktop.tsx
> +      <Box flexShrink={1} pb='x8'>
```suggestion
      <Box flexShrink={1} pb='x12'>
```

2022-08-08 14:45 UTC, ivans-netto commented
Looking great @guijun13

2022-08-10 18:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/fuselage?pullRequest=790) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/fuselage?pullRequest=790) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: guijun13<br/>:x: dougfabris<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/fuselage?pullRequest=790) it.</sub>

2022-08-11 17:04 UTC, dougfabris approved these changes

2022-08-11 17:04 UTC, merged