fix(message-rewrite): Remove emojis inside links
RocketChat/fuselage pull request #800
Opened 2022-08-09 14:58 UTC by hugocostadev

## Proposed changes (including videos or screenshots)

https:// renders an emoji in some situations
Example: 
![image](https://user-images.githubusercontent.com/20212776/183683969-bdb3dd70-452d-44cb-abc5-198b44f7a2df.png)

To fix the issue I changed the logic for grammar `domainName` 

## Issue(s)

## Further comments

2022-08-09 15:31 UTC, filipemarins requested changes
The issue is not only about the link, the issue is the emoji is being rendered in the middle of the sentence. Examples: 
`10:30` will render  1😇0. 
`he:)llo` is rendering he😄llo.  
In both scenarios it should not render the emoji.

2022-08-10 00:26 UTC, ggazzo commented
I'm sorry but the url error is a valid one and the change actually solves the issue somehow

So I dont get the comment:

> The issue is not only about the link, the issue is the emoji is being rendered in the middle of the sentence. Examples: `10:30` will render 1😇0. `he:)llo` is rendering he😄llo. In both scenarios it should not render the emoji.

2022-08-10 00:26 UTC, ggazzo submitted a review, later dismissed

2022-08-10 18:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/fuselage?pullRequest=800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/fuselage?pullRequest=800) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/fuselage?pullRequest=800) it.</sub>

2022-08-16 14:58 UTC, filipemarins submitted a review, later dismissed

2022-08-16 15:56 UTC, filipemarins approved these changes

2022-08-16 16:47 UTC, merged