feat: add disabled variant to option
RocketChat/fuselage pull request #939
Opened 2022-12-15 14:30 UTC by filipemarins

## Proposed changes (including videos or screenshots)

## Issue(s)

## Further comments

Add disabled variant to `Option` component, also move `prevent` to a helper function since it was repeating too much.

2022-12-16 15:16 UTC, aleksandernsilva submitted a review, later dismissed

2022-12-20 13:44 UTC, dougfabris requested changes

2022-12-20 13:44 UTC, dougfabris commented on packages/fuselage/src/components/Option/Option.styles.scss
> +    color: colors.font(disabled);
```suggestion
    cursor: not-allowed;
    
    color: colors.font(disabled);
```

2022-12-20 13:44 UTC, dougfabris commented on packages/fuselage/src/components/Option/Option.stories.tsx
> +export const WithDisabled: ComponentStory<typeof Option> = () => (
```suggestion
export const Disabled: ComponentStory<typeof Option> = () => (
```

2022-12-20 20:54 UTC, filipemarins commented on packages/fuselage/src/components/Option/Option.styles.scss
> +    color: colors.font(disabled);
nice

2022-12-21 20:18 UTC, dougfabris approved these changes

2022-12-21 23:45 UTC, aleksandernsilva approved these changes

2022-12-21 23:47 UTC, merged